name: Cleanup Actions

on:
  schedule:
    - cron: "0 6 * * 1"   # Mondays at 06:00 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 5
